### ISSUE TITLE
403 sur le login

### ISSUE THREAD

**Issue by zayfix** [Alphamplyer/epitech-timemanager#40]
Lors du login, même si l'utilisateur n'existe pas, le back renvoie 403 (FORBIDDEN) tandis qu'il devrait répondre 404 (Not found).

403 -> identifiant/mot de passe incorrect.
404 -> Utilisateur inexistant.

**Comment by Alphamplyer** [comment]
On ne précise en général pas la différence entre ces deux c'est plus sécurisé, ça donne moins d'indice

**Comment by Alphamplyer** [comment]
pour être plus précis ça donne pas d'info au pirate pour savoir si c'est le login ou le mot de passe qui est faux

**Comment by Alphamplyer** [comment]
du coups met login ou mot de passe invalide
